-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 20:42:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baza1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baza1` ;

-- -----------------------------------------------------
-- Schema baza1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza1` DEFAULT CHARACTER SET utf8 ;
USE `baza1` ;

-- -----------------------------------------------------
-- Table `baza1`.`id_gen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza1`.`id_gen` ;

CREATE TABLE IF NOT EXISTS `baza1`.`id_gen` (
  `gen_name` VARCHAR(50) NOT NULL,
  `gen_val` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`gen_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baza1`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza1`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `baza1`.`korisnik` (
  `JMBG` INT(11) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `BrojTelefona` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`JMBG`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baza1`.`osiguranjevozila`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza1`.`osiguranjevozila` ;

CREATE TABLE IF NOT EXISTS `baza1`.`osiguranjevozila` (
  `id` INT(11) NOT NULL,
  `KorisnikPlatio` TINYINT(4) NOT NULL,
  `korisnik_JMBG` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_osiguranje vozila_korisnik1_idx` (`korisnik_JMBG` ASC),
  CONSTRAINT `fk_osiguranje vozila_korisnik1`
    FOREIGN KEY (`korisnik_JMBG`)
    REFERENCES `baza1`.`korisnik` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baza1`.`vozilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza1`.`vozilo` ;

CREATE TABLE IF NOT EXISTS `baza1`.`vozilo` (
  `id` INT(11) NOT NULL,
  `ModelVozila` VARCHAR(45) NOT NULL,
  `Kubikaza` INT(11) NOT NULL,
  `Jacina` INT(11) NOT NULL,
  `korisnik_JMBG` INT(11) NOT NULL,
  `osigurano` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vozilo_korisnik_idx` (`korisnik_JMBG` ASC),
  CONSTRAINT `fk_vozilo_korisnik`
    FOREIGN KEY (`korisnik_JMBG`)
    REFERENCES `baza1`.`korisnik` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
